name: Encryptionapi2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --configuration Release

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      - name: Zip published files
        run: |
          cd publish
          zip -r ../site.zip ./*
          cd ..

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-north-1
          application_name: Mimmi1
          environment_name: Mimmi1-env
          version_label: ${{ github.run_id }}
          deployment_package: site.zip

