name: Build-aws
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.405'

      - name: Build and Publish projekt
        run: |
          dotnet restore 
          dotnet publish -c Release -o ./publish

      - name: Create zip package
        run: |
          cd ./publish
          zip -r ../ApiProjekt.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "mimmi 1"
          environment_name: "Mimmi1-env"
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: ApiProjekt.zip
